# Generated by Django 3.2.13 on 2022-04-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
                ('site', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.IntegerField()),
            ],
        ),
    ]
