# Generated by Django 3.2.13 on 2022-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Depot3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Depot',
            new_name='Depot1',
        ),
    ]
